#!/bin/bash

git branch gh-pages

npm run build

git add dist

if [[ $1 = '-m' ]]
then
  if [[ $2 != '' ]]
  then
    git commit -m $2
  else
    echo "Error: -m option given without message"
    exit 1
  fi
else
  git commit -m "Wip"
fi

git subtree push --prefix dist origin gh-pages

exit 0
